//
//  CityPicker.swift
//  Directist
//
//  Created by Alex on 14/11/14.
//  Copyright (c) 2014 Chalkbox Creatives. All rights reserved.
//

import UIKit

typealias DidPickCity = (city: String) -> Void

class CityPicker: UIView, UIPickerViewDataSource, UIPickerViewDelegate {
    var didPickCity: DidPickCity!
    @IBOutlet weak var pickerView: UIPickerView!
    
    var cities : NSMutableArray! = NSMutableArray(capacity: 0)
    
    override func awakeFromNib() {
        cities.addObjectsFromArray([
            "All Cities",
            "Kabul, Afghanistan",
            "Tirana, Albania",
            "Algiers, Algeria",
            "Pago Pago, American Samoa (USA)",
            "Andorra La Vella, Andorra",
            "Luanda, Angola",
            "The Valley, Anguilla (UK)",
            "Saint Johns,Antigua and Barbuda",
            "Buenos Aires, Argentina",
            "Yerevan, Armenia",
            "Oranjestad, Aruba (Netherlands)",
            "Canberra, Australia",
            "Vienna, Austria",
            "Baku, Azerbaijan",
            "Nassau, Bahamas",
            "Manama, Bahrain",
            "Dhaka, Bangladesh",
            "Bridgetown, Barbados",
            "Minsk, Belarus",
            "Brussels, Belgium",
            "Belmopan, Belize",
            "Porto-Novo,Benin",
            "Hamilton, Bermuda (UK)",
            "Thimphu, Bhutan",
            "Sucre,Bolivia",
            "Sarajevo, Bosnia and Herzegovina",
            "Gaborone, Botswana",
            "Brasília, Brazil",
            "Road Town, British Virgin Islands (UK)",
            "Bandar Seri Begawan, Brunei",
            "Sofia, Bulgaria",
            "Ouagadougou, Burkina Faso",
            "Bujumbura, Burundi",
            "Phnom Penh, Cambodia",
            "Yaoundé, Cameroon",
            "Ottawa, Canada",
            "Praia, Cape Verde",
            "George Town, Cayman Islands (UK)",
            "Bangui, Central African Republic",
            "N'Djamena, Chad",
            "Santiago, Chile",
            "Beijing, China",
            "Flying Fish Cove, Christmas Island (Australia)",
            "West Island, Cocos Islands, Cocos (Keeling) Islands (Australia)",
            "Bogotá, Colombia",
            "Moroni, Comoros",
            "Avarua, Cook Islands (New Zealand)",
            "San José, Costa Rica",
            "Zagreb, Croatia",
            "Havana, Cuba",
            "Willemstad, Curacao (Netherlands)",
            "Nicosia, Cyprus",
            "Prague, Czech Republic",
            "Kinshasa, D.R Congo",
            "Copenhagen, Denmark",
            "Djibouti-city,Djibouti",
            "Roseau, Dominica",
            "Santo Domingo, Dominican Republic",
            "Dili, East Timor (Timor-Leste)",
            "Quito, Ecuador",
            "Cairo, Egypt",
            "San Salvador, El Salvador",
            "Malabo, Equatorial Guinea",
            "Asmara, Eritrea",
            "Tallinn, Estonia",
            "Addis Ababa, Ethiopia",
            "Stanley, Falkland Islands (UK)",
            "Tórshavn, Faroe Islands (Denmark)",
            "Suva, Fiji",
            "Helsinki, Finland",
            "Paris, France",
            "Cayenne, French Guiana (France)",
            "Papeete, French Polynesia (France)",
            "Libreville, Gabon",
            "Banjul, Gambia",
            "Tbilisi, Georgia",
            "Berlin, Germany",
            "Accra, Ghana",
            "Gibraltar, Gibraltar (UK)",
            "Athens, Greece",
            "Nuuk, Greenland (Denmark)",
            "St. George's, Grenada",
            "Hagatna, Guam (USA)",
            "Guatemala City,Guatemala",
            "Saint Peter Port,Guernsey (UK)",
            "Conakry, Guinea",
            "Bissau, Guinea-Bissau",
            "Georgetown, Guyana",
            "Port-au-prince, Haiti",
            "Tegucigalpa, Honduras",
            "Hong Kong City,Hong Kong (China)",
            "Budapest, Hungary",
            "Reykjavík, Iceland",
            "New Delhi, India",
            "Jakarta, Indonesia",
            "Tehran, Iran",
            "Baghdad, Iraq",
            "Dublin, Ireland",
            "Douglas, Isle of Man (UK)",
            "Jerusalem,Israel",
            "Rome, Italy",
            "Yamoussoukro,Ivory Coast",
            "Kingston, Jamaica",
            "Tokyo, Japan",
            "Saint Helier,Jersey (UK)",
            "Amman, Jordan",
            "Astana, Kazakhstan",
            "Nairobi, Kenya",
            "Tarawa, Kiribati",
            "Pristina, Kosovo",
            "Kuwait City, Kuwait",
            "Bishkek, Kyrgyzstan",
            "Vientiane, Laos",
            "Riga, Latvia",
            "Beirut, Lebanon",
            "Maseru, Lesotho",
            "Monrovia, Liberia",
            "Tripoli, Libya",
            "Vaduz, Liechtenstein",
            "Vilnius, Lithuania",
            "Luxembourg, Luxembourg",
            "Skopje, Macedonia",
            "Antananarivo, Madagascar",
            "Lilongwe, Malawi",
            "Kuala Lumpur, Malaysia",
            "Malé, Maldives",
            "Bamako, Mali",
            "Valletta, Malta",
            "Majuro, Marshall Islands",
            "Nouakchott, Mauritania",
            "Port Louis, Mauritius",
            "Mexico City, Mexico",
            "Palikir, Micronesia",
            "Chisinau, Moldova",
            "Monaco, Monaco",
            "Ulan Bator, Mongolia",
            "Podgorica, Montenegro",
            "Brades, Plymouth,Montserrat (UK)",
            "Rabat, Morocco",
            "Maputo, Mozambique",
            "Naypyidaw, Myanmar",
            "Windhoek, Namibia",
            "Yaren,Nauru",
            "Kathmandu, Nepal",
            "Amsterdam, Netherlands",
            "Nouméa, New Caledonia (France)",
            "Wellington, New Zealand",
            "Managua, Nicaragua",
            "Niamey, Niger",
            "Abuja, Nigeria",
            "Alofi, Niue (New Zealand)",
            "Kingston, Norfolk Island (Australia)",
            "Pyongyang, North Korea",
            "Saipan, Northern Mariana Islands (USA)",
            "Oslo, Norway",
            "Muscat, Oman",
            "Islamabad, Pakistan",
            "Ngerulmud, Palau",
            "Ramallah and Gaza,Palestine",
            "Panama City, Panama",
            "Port Moresby, Papua New Guinea",
            "Asunción, Paraguay",
            "Lima, Peru",
            "Manila, Philippines",
            "Adamstown, Pitcairn Islands (UK)",
            "Warsaw, Poland",
            "Lisbon, Portugal",
            "San Juan, Puerto Rico (USA)",
            "Doha, Qatar",
            "Brazzaville, Republic of the Congo",
            "Bucharest, Romania",
            "Moscow, Russia",
            "Kigali, Rwanda",
            "Gustavia, Saint Barthélemy,Saint Barthelemy",
            "Jamestown,Saint Helena, Ascension, and Tristan da Cunha (UK)",
            "Basseterre, Saint Kitts and Nevis",
            "Castries, Saint Lucia",
            "Philipsburg,Saint Martin",
            "Saint-Pierre,Saint Pierre and Miquelon (France)",
            "Kingstown, Saint Vincent and the Grenadines",
            "Apia, Samoa",
            "San Marino, San Marino",
            "Sao Tome,São Tomé and Príncipe",
            "Riyadh, Saudi Arabia",
            "Dakar, Senegal",
            "Belgrade, Serbia",
            "Victoria, Seychelles",
            "Freetown, Sierra Leone",
            "Singapore, Singapore",
            "Philipsburg,Sint Maarten (Netherlands)",
            "Bratislava, Slovakia",
            "Ljubljana, Slovenia",
            "Honiara, Solomon Islands",
            "Mogadishu, Somalia",
            "Cape Town,South Africa",
            "Seoul, South Korea",
            "Juba, South Sudan",
            "Madrid, Spain",
            "Sri Jayawardenapura-kotte,Sri Lanka",
            "Khartoum, Sudan",
            "Paramaribo, Suriname",
            "Mata-utu, Swaziland",
            "Stockholm, Sweden",
            "Bern, Switzerland",
            "Damascus, Syria",
            "Taipei, Taiwan",
            "Dushanbe, Tajikistan",
            "Dodoma,Tanzania",
            "Bangkok, Thailand",
            "Lomé, Togo",
            "Nukunonu, Atafu,Tokelau,Tokelau (New Zealand)",
            "Nukuʻalofa, Tonga",
            "Tiraspol, Transnistria",
            "Port Of Spain, Trinidad and Tobago",
            "Tunis, Tunisia",
            "Ankara, Turkey",
            "Ashgabat, Turkmenistan",
            "Cockburn Town, Turks and Caicos Islands (UK)",
            "Funafuti, Tuvalu",
            "Kampala, Uganda",
            "Kiev, Ukraine",
            "Abu Dhabi, United Arab Emirates",
            "London, United Kingdom",
            "Washington D.C., United States",
            "Charlotte Amalie, United States Virgin Islands (USA)",
            "Montevideo, Uruguay",
            "Tashkent, Uzbekistan",
            "Port Vila, Vanuatu",
            "Vatican City, Vatican City",
            "Caracas, Venezuela",
            "Hanoi, Vietnam",
            "Mata-Utu, Wallis and Futuna (France)",
            "El Aaiun,Western Sahara",
            "Sana'a, Yemen",
            "Lusaka, Zambia",
            "Harare, Zimbabwe"])
    }
    
    func pickerView(pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return cities.count
    }
    
    func pickerView(pickerView: UIPickerView, rowHeightForComponent component: Int) -> CGFloat {
        return 44
    }
    
    func numberOfComponentsInPickerView(pickerView: UIPickerView) -> Int {
        return 1
    }
    
    func pickerView(pickerView: UIPickerView, viewForRow row: Int, forComponent component: Int, reusingView view: UIView?) -> UIView {
        let label: UILabel = UILabel()
        label.font = UIFont(name:"GillSans", size: 20)
        label.textAlignment = .Center
        label.text = cities[row] as! String as String
        label.frame = CGRectMake(0, 0, self.bounds.size.width, 44)
        
        return label
    }
    
    func pickerView(pickerView: UIPickerView, didSelectRow row: Int, inComponent component: Int) {
        if row < cities.count {
            if didPickCity != nil {
                didPickCity(city: cities[row] as! String)
            }
        }
    }
}
